# Generated by Django 3.0.3 on 2020-02-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taulutaulu',
            name='hinta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taulutaulu',
            name='koko',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='taulutaulu',
            name='kuva',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='taulutaulu',
            name='materiaali',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='taulutaulu',
            name='vuosi',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
