# Generated by Django 3.0.3 on 2020-02-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taide', '0002_auto_20200219_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='KysyTaulusta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maili', models.EmailField(max_length=254)),
                ('taide', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
