# Generated by Django 3.0.3 on 2020-03-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taide', '0004_auto_20200301_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='kysytaulusta',
            name='aika',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
